#This code is used to run nicheROVER analysis and produce associated figures (4A, 4B, S3, S5)
#Based on Swanson et al. 2015: A new probabilistic method for quantifying n-dimensional ecological niches and niche overlap
#Code edited by G. Busquets-Vass, C.E. Meyer and C. Smith for false killer whale analysis 
#The data used here have been QC-ed and the carbon isotope values have been Suess-corrected 

### CLEAN EVERYTHING ###
rm(list=ls())
graphics.off() # close all 
gc() # Clear memory 

#install library 
library(nicheROVER)

#set working directory 
setwd("your/file/directory/here")

#1 upload and organise data -  each sample partition must be labelled properly 
fkw_nz <- read.csv("your_filename_here.csv", header=TRUE)
fkw_nz
aggregate(fkw_nz[7:8], fkw_nz[3], mean) # note [7:8] refers to N and C columns in .csv file 

#analysis for all sample partition data
#2 generate parameter draws from the default posteriors of each group of samples 

nsamples <- 10000
system.time({
  fkw_nz.par <- tapply(1:nrow(fkw_nz),  fkw_nz$Group,
                        function(ii) niw.post(nsamples = nsamples, X = fkw_nz[ii,7:8]))
})

#3 various parameter plots
clrs.2 <- c("#cc0044","#F0E442","#004151","#00ccff", "#8FD744","#00ff66","#006600")# colors for each group
               

#Groups to colours above:  AUS_B, FIS_S, NZ_S_Rēkohu, NZ_S_Māhia, NZ_B_1_early, NZ_B_1_late, NZ_B_2

# Produce plots for mu1 (d15N), mu2 (d13C), and Sigma1,2

png(filename = "muandsigma_figure.png", width = 30, height = 20, units = 'cm', res = 400) #save a plot

par(mar = c(4, 4, .5, .1)+.1, mfrow = c(1,3))
niche.par.plot(fkw_nz.par, col = clrs.2, plot.index = 1)
niche.par.plot(fkw_nz.par, col = clrs.2, plot.index = 2)
niche.par.plot(fkw_nz.par, col = clrs.2, plot.index = 1:2)
legend("topleft", legend = c("AUS_B","FIS_S","NZ_S_Rēkohu", "NZ_S_Māhia", "NZ_B_1_early", "NZ_B_1_late", "NZ_B_2"), 
       fill = clrs.2, bty = "n") #create legend using specified colours, remove box around it 

dev.off()


# all mu (del15N, del13C) plots but not sigma

png(filename = "muonly_figure.png", width = 35, height = 20, units = 'cm', res = 400) #save a plot

niche.par.plot(fkw_nz.par, col = clrs.2, plot.mu = TRUE, plot.Sigma = FALSE)
legend("topright", legend = c("AUS_B","FIS_S","NZ_S_Rēkohu", "NZ_S_Māhia", "NZ_B_1_early", "NZ_B_1_late", "NZ_B_2"), 
       fill = clrs.2, bty = "n")

dev.off()

# all mu and Sigma plots 
png(filename = "allmuandsigma_figure.png", width = 30, height = 20, units = 'cm', res = 400) #save a plot

par(mar = c(4.2, 4.2, 2, 1)+.1)
niche.par.plot(fkw_nz.par, col = clrs.2, plot.mu = TRUE, plot.Sigma = TRUE)
legend("topright", legend = c( "AUS_B","FIS_S","NZ_S_Rēkohu", "NZ_S_Māhia", "NZ_B_1_early", "NZ_B_1_late", "NZ_B_2"),
       fill = clrs.2, bty = "n")

dev.off()


#Create 2-d projections of a subset of niche regions
#See ?niche.plot for more details on parameter values.

#Here, we have chosen to display 10 random niche regions generated by the Bayesian analysis. The parameter list fkw_nz.par is generated using the niw.post() function provided by nicheROVER.
#The resulting figure generates niche plots, density distributions, and raw data for each pairwise combination of isotope data for all groups (i.e., bivariate projections of 2-dimensional isotope data).


#4 produce 2-d projections of 10 niche regions
#use same colours as specified above 
#this produces Figures 4A and S5

clrs.2 <- c("#cc0044","#F0E442","#004151","#00ccff", "#8FD744","#00ff66","#006600")# colors for each group


nsamples <- 10
fkw_nz.par <- tapply(1:nrow(fkw_nz), fkw_nz$Group,
                      function(ii) niw.post(nsamples = nsamples, X = fkw_nz[ii,7:8]))

# format data for plotting function
fkw_nz.data <- tapply(1:nrow(fkw_nz), fkw_nz$Group, function(ii) X = fkw_nz[ii,7:8])

png(filename = "nicheplot.png", width = 41, height = 25, units = 'cm', res = 400) #save a plot

niche.plot(niche.par = fkw_nz.par, niche.data = fkw_nz.data, pfrac = .05,
           iso.names = expression(delta^{15}*N, delta^{13}*C),
           col = clrs.2, xlab = expression("Isotope Ratio (\u2030)"), species.names = c("AUS_B","FIS_S","NZ_S_Rēkohu", "NZ_S_Māhia", "NZ_B_1_early", "NZ_B_1_late", "NZ_B_2"),
           legend = TRUE) 
 

dev.off()

#5. Calculate and display niche overlap estimates
#We use the function overlap() to calculate overlap metric estimates from a specified number of Monte Carlo draws (nsamples) from the fkw_all.par parameter list. It is necessary to specify the α
#-level. In this case, we have decided to calculate the overlap metric at two niche regions sizes for comparison: alpha=0.95 and alpha=0.99, or 95% and 99%.

#Then, we calculate the mean overlap metric between each species. Remember that the overlap metric is directional, such that it represents the probability that an individual from Species A
#will be found in the niche of Species B


# niche overlap plots for 95% niche region sizes
nsamples <- 10000
fkw_nz.par <- tapply(1:nrow(fkw_nz), fkw_nz$Group,
                      function(ii) niw.post(nsamples = nsamples, X = fkw_nz[ii,7:8]))

# Overlap calculation.  use nsamples = nprob = 10000 (1e4) for higher accuracy.
# the variable over.stat can be supplied directly to the overlap.plot function

over.stat <- overlap(fkw_nz.par, nreps = nsamples, nprob = 1e4, alpha = c(.95, .99))

#The mean overlap metrics calculated across iterations for both niche region sizes (alpha = .95 and alpha = .99) 
#can be calculated and displayed in an array.
over.mean <- apply(over.stat, c(1:2,4), mean)*100
round(over.mean, 2)


over.cred <- apply(over.stat*100, c(1:2, 4), quantile, prob = c(.025, .975), na.rm = TRUE)
over.cred
round(over.cred[,,,2]) # display alpha = .95 niche region

#In the returned plot, Species A is along the rows and Species B is along columns. The plots represent the posterior probability that an individual from the species indicated by the row will be found within the niche of the species indicated by the column header. Before you plot, you must decide upon your α
#-level, and make sure the variable over.stat reflects this choice of α


#Overlap plot.Before you run this, make sure that you have chosen your alpha level.
#this produces Figure S3

clrs.2 <- c("#cc0044","#F0E442","#004151","#00ccff", "#8FD744","#00ff66","#006600")# colors for each group


png(filename = "overlap_plot.png", width = 50, height = 30, units = 'cm', res = 400) #save a plot

over.stat <- overlap(fkw_nz.par, nreps = nsamples, nprob = 1e4, alpha = .95) #alpha = 0.95
custom.names <- c("AUS_B","FIS_S","NZ_S_Rēkohu", "NZ_S_Māhia", "NZ_B_1_early", "NZ_B_1_late", "NZ_B_2")
overlap.plot(over.stat, col = clrs.2, mean.cred.col = "#000000", equal.axis = TRUE,
             xlab = "Overlap Probability (%) -- Niche Region Size: 95%", species.names = custom.names)

dev.off()

#6. Calculate and display niche size estimates
#See ?niche.size for exactly how niche size is defined as a function of the parameters μ and Σ
# In a Bayesian context, we calculate the posterior distribution of niche size by species. This done by calculating the niche size for every posterior sample of μ and Σ


# posterior distribution of (mu, Sigma) for each group
nsamples <- 10000
fkw_nz.par <- tapply(1:nrow(fkw_nz), fkw_nz$Group,
                      function(ii) niw.post(nsamples = nsamples, X = fkw_nz[ii,7:8]))

# posterior distribution of niche size by group
fkw_nz.size <- sapply(fkw_nz.par, function(spec) {
  apply(spec$Sigma, 3, niche.size, alpha = .95)
})


summary(fkw_nz.size)

# point estimate and standard error
rbind(est = colMeans(fkw_nz.size),
      se = apply(fkw_nz.size, 2, sd))

par(mfrow=c(1,1))

# boxplots
clrs.2 <- c("#cc0044","#F0E442","#004151","#00ccff", "#8FD744","#00ff66","#006600")# colors for each group
boxplot(log(fkw_nz.size), col = clrs.2, pch = 16, cex = 0.5, ylim = c(-2,3),
        ylab = "Niche Size", xlab = "Sample Partitions", outline=FALSE)


#use SIBER to plot niche size - use colour matrix to make box plots, ensure they align with the correct group
#this produces Figure 4B 

library(SIBER)
dev.new() # Also use to save the graph
png(filename = "nichesize_plot.png", width = 40, height = 20, units = 'cm', res = 400) #save a plot
par(mar=c(4,4,4,4))
clr3 <- matrix (c ("#FF9999","#cc0044","#660033",
                   "#ffff66","#F0E442","#d1bd04",
                   "#007e9e","#00556b","#004151",
                   "#89e7ff","#00ccff","#00add8",
                   "#bfe895","#8FD744","#406816",
                   "#9dffc4","#00ff66","#00c44e",
                   "#00c800","#006600","#003f00")
                   
                , nrow = 3, ncol = 7, byrow = FALSE)

siberDensityPlot(fkw_nz.size, 
                 clr = clr3, 
                 xlab = c('Sample Partition'),
                 xticklabels = c("AUS_B","FIS_S","NZ_S_Rēkohu", "NZ_S_Māhia", "NZ_B_1_early", "NZ_B_1_late", "NZ_B_2"),
                 ylab = expression("Standard Ellipse Area"[B] ('\u2030' ^2)),
                 bty = "L",
                 las = 1,
                 ylims = c(0, 4), # Change limits
)
dev.off() 

#Note that figures 4A and 4B were edited further in Powerpoint 
